/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cliu_TutorialOnFaceDetect_TutorialOnFaceDetect */

#ifndef _Included_cliu_TutorialOnFaceDetect_TutorialOnFaceDetect
#define _Included_cliu_TutorialOnFaceDetect_TutorialOnFaceDetect
#ifdef __cplusplus
extern "C" {
#endif
#undef cliu_TutorialOnFaceDetect_TutorialOnFaceDetect_MAX_FACES
#define cliu_TutorialOnFaceDetect_TutorialOnFaceDetect_MAX_FACES 10L
#undef cliu_TutorialOnFaceDetect_TutorialOnFaceDetect_GUIUPDATE_SETFACE
#define cliu_TutorialOnFaceDetect_TutorialOnFaceDetect_GUIUPDATE_SETFACE 999L
/*
 * Class:     cliu_TutorialOnFaceDetect_TutorialOnFaceDetect
 * Method:    sendToC
 * Signature: (II[I)[I
 */
JNIEXPORT jintArray JNICALL Java_cliu_TutorialOnFaceDetect_TutorialOnFaceDetect_sendToC
  (JNIEnv *, jobject, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
